
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorJS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comm = 9;
  public static final int pclass = 22;
  public static final int mod = 7;
  public static final int llave_i = 11;
  public static final int pcase = 37;
  public static final int llave_d = 12;
  public static final int com = 8;
  public static final int log = 26;
  public static final int coma = 13;
  public static final int igual = 10;
  public static final int pdo = 36;
  public static final int ptcoma = 16;
  public static final int name = 41;
  public static final int let = 33;
  public static final int brk = 27;
  public static final int pswitch = 28;
  public static final int pdef = 21;
  public static final int menos = 44;
  public static final int pwhile = 35;
  public static final int menor = 6;
  public static final int digitos = 40;
  public static final int var = 32;
  public static final int EOF = 0;
  public static final int mas = 2;
  public static final int ptrue = 19;
  public static final int error = 1;
  public static final int mayor = 5;
  public static final int entero = 38;
  public static final int or = 30;
  public static final int pfalse = 20;
  public static final int por = 4;
  public static final int punto = 43;
  public static final int req = 18;
  public static final int cons = 25;
  public static final int pif = 23;
  public static final int pelse = 24;
  public static final int pfor = 17;
  public static final int pconst = 34;
  public static final int and = 29;
  public static final int not = 31;
  public static final int par_i = 14;
  public static final int d_punto = 42;
  public static final int par_d = 15;
  public static final int div = 3;
  public static final int cadena = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "div",
  "por",
  "mayor",
  "menor",
  "mod",
  "com",
  "comm",
  "igual",
  "llave_i",
  "llave_d",
  "coma",
  "par_i",
  "par_d",
  "ptcoma",
  "pfor",
  "req",
  "ptrue",
  "pfalse",
  "pdef",
  "pclass",
  "pif",
  "pelse",
  "cons",
  "log",
  "brk",
  "pswitch",
  "and",
  "or",
  "not",
  "var",
  "let",
  "pconst",
  "pwhile",
  "pdo",
  "pcase",
  "entero",
  "cadena",
  "digitos",
  "name",
  "d_punto",
  "punto",
  "menos"
  };
}

