
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorJS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pclass = 20;
  public static final int mod = 7;
  public static final int llave_i = 9;
  public static final int pcase = 35;
  public static final int llave_d = 10;
  public static final int log = 24;
  public static final int coma = 11;
  public static final int igual = 8;
  public static final int pdo = 34;
  public static final int ptcoma = 14;
  public static final int name = 39;
  public static final int let = 31;
  public static final int brk = 25;
  public static final int pswitch = 26;
  public static final int pdef = 19;
  public static final int menos = 42;
  public static final int pwhile = 33;
  public static final int menor = 6;
  public static final int digitos = 38;
  public static final int var = 30;
  public static final int EOF = 0;
  public static final int mas = 2;
  public static final int ptrue = 17;
  public static final int error = 1;
  public static final int mayor = 5;
  public static final int entero = 36;
  public static final int or = 28;
  public static final int pfalse = 18;
  public static final int por = 4;
  public static final int punto = 41;
  public static final int req = 16;
  public static final int cons = 23;
  public static final int pif = 21;
  public static final int pelse = 22;
  public static final int pfor = 15;
  public static final int pconst = 32;
  public static final int and = 27;
  public static final int not = 29;
  public static final int par_i = 12;
  public static final int d_punto = 40;
  public static final int par_d = 13;
  public static final int div = 3;
  public static final int cadena = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "div",
  "por",
  "mayor",
  "menor",
  "mod",
  "igual",
  "llave_i",
  "llave_d",
  "coma",
  "par_i",
  "par_d",
  "ptcoma",
  "pfor",
  "req",
  "ptrue",
  "pfalse",
  "pdef",
  "pclass",
  "pif",
  "pelse",
  "cons",
  "log",
  "brk",
  "pswitch",
  "and",
  "or",
  "not",
  "var",
  "let",
  "pconst",
  "pwhile",
  "pdo",
  "pcase",
  "entero",
  "cadena",
  "digitos",
  "name",
  "d_punto",
  "punto",
  "menos"
  };
}

