
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tipo_s = 33;
  public static final int title_y = 40;
  public static final int title_x = 39;
  public static final int llave_i = 7;
  public static final int pdefinir = 27;
  public static final int coma_f = 13;
  public static final int cor_i = 14;
  public static final int llave_d = 8;
  public static final int tipo_d = 34;
  public static final int coma = 9;
  public static final int igual = 6;
  public static final int cor_d = 15;
  public static final int ptcoma = 12;
  public static final int name = 20;
  public static final int pejex = 36;
  public static final int pcomp = 32;
  public static final int menos = 26;
  public static final int digitos = 19;
  public static final int EOF = 0;
  public static final int comillas = 25;
  public static final int mas = 2;
  public static final int error = 1;
  public static final int pvalue = 37;
  public static final int entero = 17;
  public static final int por = 4;
  public static final int title = 35;
  public static final int punto = 24;
  public static final int pgrafp = 30;
  public static final int pfile = 38;
  public static final int pgrafl = 31;
  public static final int dolar = 16;
  public static final int hash = 5;
  public static final int par_i = 10;
  public static final int pgrafb = 29;
  public static final int esp_pt = 22;
  public static final int d_punto = 23;
  public static final int gen_pt = 21;
  public static final int par_d = 11;
  public static final int div = 3;
  public static final int preporte = 28;
  public static final int cadena = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "div",
  "por",
  "hash",
  "igual",
  "llave_i",
  "llave_d",
  "coma",
  "par_i",
  "par_d",
  "ptcoma",
  "coma_f",
  "cor_i",
  "cor_d",
  "dolar",
  "entero",
  "cadena",
  "digitos",
  "name",
  "gen_pt",
  "esp_pt",
  "d_punto",
  "punto",
  "comillas",
  "menos",
  "pdefinir",
  "preporte",
  "pgrafb",
  "pgrafp",
  "pgrafl",
  "pcomp",
  "tipo_s",
  "tipo_d",
  "title",
  "pejex",
  "pvalue",
  "pfile",
  "title_x",
  "title_y"
  };
}

