
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comm = 21;
  public static final int title_y = 40;
  public static final int title_x = 39;
  public static final int llave_i = 8;
  public static final int pdefinir = 27;
  public static final int coma_f = 14;
  public static final int cor_i = 17;
  public static final int llave_d = 9;
  public static final int com = 20;
  public static final int coma = 10;
  public static final int igual = 7;
  public static final int cor_d = 18;
  public static final int letra = 25;
  public static final int ptcoma = 13;
  public static final int name = 26;
  public static final int pejex = 36;
  public static final int menos = 3;
  public static final int digitos = 24;
  public static final int EOF = 0;
  public static final int mas = 2;
  public static final int error = 1;
  public static final int tstring = 33;
  public static final int pvalue = 37;
  public static final int entero = 22;
  public static final int por = 5;
  public static final int title = 35;
  public static final int punto = 16;
  public static final int pgrafp = 30;
  public static final int pfile = 38;
  public static final int pgrafl = 31;
  public static final int dolar = 19;
  public static final int hash = 6;
  public static final int par_i = 11;
  public static final int pgrafb = 29;
  public static final int d_punto = 15;
  public static final int tdouble = 34;
  public static final int par_d = 12;
  public static final int div = 4;
  public static final int pcompare = 32;
  public static final int preporte = 28;
  public static final int cadena = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "div",
  "por",
  "hash",
  "igual",
  "llave_i",
  "llave_d",
  "coma",
  "par_i",
  "par_d",
  "ptcoma",
  "coma_f",
  "d_punto",
  "punto",
  "cor_i",
  "cor_d",
  "dolar",
  "com",
  "comm",
  "entero",
  "cadena",
  "digitos",
  "letra",
  "name",
  "pdefinir",
  "preporte",
  "pgrafb",
  "pgrafp",
  "pgrafl",
  "pcompare",
  "tstring",
  "tdouble",
  "title",
  "pejex",
  "pvalue",
  "pfile",
  "title_x",
  "title_y"
  };
}

